package com.healthLife.DAO.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ALIMEN_RESTRING.
 */
public class AlimenRestring {

    private Long id;
    private Long id_enfermedad;
    private Long id_alimento;

    public AlimenRestring() {
    }

    public AlimenRestring(Long id) {
        this.id = id;
    }

    public AlimenRestring(Long id, Long id_enfermedad, Long id_alimento) {
        this.id = id;
        this.id_enfermedad = id_enfermedad;
        this.id_alimento = id_alimento;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getId_enfermedad() {
        return id_enfermedad;
    }

    public void setId_enfermedad(Long id_enfermedad) {
        this.id_enfermedad = id_enfermedad;
    }

    public Long getId_alimento() {
        return id_alimento;
    }

    public void setId_alimento(Long id_alimento) {
        this.id_alimento = id_alimento;
    }

}
