package com.healthLife.DAO.model;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.healthLife.DAO.model.DiarioLista;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table DIARIO_LISTA.
*/
public class DiarioListaDao extends AbstractDao<DiarioLista, Long> {

    public static final String TABLENAME = "DIARIO_LISTA";

    /**
     * Properties of entity DiarioLista.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Id_diario = new Property(1, Long.class, "id_diario", false, "ID_DIARIO");
        public final static Property Id_alimento = new Property(2, Long.class, "id_alimento", false, "ID_ALIMENTO");
        public final static Property Porcion = new Property(3, Double.class, "porcion", false, "PORCION");
    };


    public DiarioListaDao(DaoConfig config) {
        super(config);
    }
    
    public DiarioListaDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'DIARIO_LISTA' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'ID_DIARIO' INTEGER," + // 1: id_diario
                "'ID_ALIMENTO' INTEGER," + // 2: id_alimento
                "'PORCION' REAL);"); // 3: porcion
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'DIARIO_LISTA'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, DiarioLista entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long id_diario = entity.getId_diario();
        if (id_diario != null) {
            stmt.bindLong(2, id_diario);
        }
 
        Long id_alimento = entity.getId_alimento();
        if (id_alimento != null) {
            stmt.bindLong(3, id_alimento);
        }
 
        Double porcion = entity.getPorcion();
        if (porcion != null) {
            stmt.bindDouble(4, porcion);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public DiarioLista readEntity(Cursor cursor, int offset) {
        DiarioLista entity = new DiarioLista( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // id_diario
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2), // id_alimento
            cursor.isNull(offset + 3) ? null : cursor.getDouble(offset + 3) // porcion
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, DiarioLista entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setId_diario(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setId_alimento(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
        entity.setPorcion(cursor.isNull(offset + 3) ? null : cursor.getDouble(offset + 3));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(DiarioLista entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(DiarioLista entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
