package com.healthLife.DAO.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table DIARIO.
 */
public class Diario {

    private Long id;
    private Long id_admin;
    private java.util.Date fecha;
    private Double tot_calorias;
    private Double tot_grasa;
    private Double tot_proteina;
    private Double tot_carbo;

    public Diario() {
    }

    public Diario(Long id) {
        this.id = id;
    }

    public Diario(Long id, Long id_admin, java.util.Date fecha, Double tot_calorias, Double tot_grasa, Double tot_proteina, Double tot_carbo) {
        this.id = id;
        this.id_admin = id_admin;
        this.fecha = fecha;
        this.tot_calorias = tot_calorias;
        this.tot_grasa = tot_grasa;
        this.tot_proteina = tot_proteina;
        this.tot_carbo = tot_carbo;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getId_admin() {
        return id_admin;
    }

    public void setId_admin(Long id_admin) {
        this.id_admin = id_admin;
    }

    public java.util.Date getFecha() {
        return fecha;
    }

    public void setFecha(java.util.Date fecha) {
        this.fecha = fecha;
    }

    public Double getTot_calorias() {
        return tot_calorias;
    }

    public void setTot_calorias(Double tot_calorias) {
        this.tot_calorias = tot_calorias;
    }

    public Double getTot_grasa() {
        return tot_grasa;
    }

    public void setTot_grasa(Double tot_grasa) {
        this.tot_grasa = tot_grasa;
    }

    public Double getTot_proteina() {
        return tot_proteina;
    }

    public void setTot_proteina(Double tot_proteina) {
        this.tot_proteina = tot_proteina;
    }

    public Double getTot_carbo() {
        return tot_carbo;
    }

    public void setTot_carbo(Double tot_carbo) {
        this.tot_carbo = tot_carbo;
    }

}
