package com.healthLife.DAO.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table FAMILIAR.
 */
public class Familiar {

    private Long id;
    private Long id_persona;
    private Long id_usuario;

    public Familiar() {
    }

    public Familiar(Long id) {
        this.id = id;
    }

    public Familiar(Long id, Long id_persona, Long id_usuario) {
        this.id = id;
        this.id_persona = id_persona;
        this.id_usuario = id_usuario;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getId_persona() {
        return id_persona;
    }

    public void setId_persona(Long id_persona) {
        this.id_persona = id_persona;
    }

    public Long getId_usuario() {
        return id_usuario;
    }

    public void setId_usuario(Long id_usuario) {
        this.id_usuario = id_usuario;
    }

}
