package com.healthLife.DAO.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table LIST_ENFERMEDAD.
 */
public class ListEnfermedad {

    private Long id;
    private Long id_persona;
    private Long id_enfermedad;

    public ListEnfermedad() {
    }

    public ListEnfermedad(Long id) {
        this.id = id;
    }

    public ListEnfermedad(Long id, Long id_persona, Long id_enfermedad) {
        this.id = id;
        this.id_persona = id_persona;
        this.id_enfermedad = id_enfermedad;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getId_persona() {
        return id_persona;
    }

    public void setId_persona(Long id_persona) {
        this.id_persona = id_persona;
    }

    public Long getId_enfermedad() {
        return id_enfermedad;
    }

    public void setId_enfermedad(Long id_enfermedad) {
        this.id_enfermedad = id_enfermedad;
    }

}
