package com.healthLife.DAO.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table MENU.
 */
public class Menu {

    private Long id;
    private String nomDes;
    private String nomAlmu;
    private String nomMeri;

    public Menu() {
    }

    public Menu(Long id) {
        this.id = id;
    }

    public Menu(Long id, String nomDes, String nomAlmu, String nomMeri) {
        this.id = id;
        this.nomDes = nomDes;
        this.nomAlmu = nomAlmu;
        this.nomMeri = nomMeri;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getNomDes() {
        return nomDes;
    }

    public void setNomDes(String nomDes) {
        this.nomDes = nomDes;
    }

    public String getNomAlmu() {
        return nomAlmu;
    }

    public void setNomAlmu(String nomAlmu) {
        this.nomAlmu = nomAlmu;
    }

    public String getNomMeri() {
        return nomMeri;
    }

    public void setNomMeri(String nomMeri) {
        this.nomMeri = nomMeri;
    }

}
