package com.healthLife.DAO.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table TEMP_ALIMENTO.
 */
public class TempAlimento {

    private Long id;
    private Long id_alimento;
    private String nombre;

    public TempAlimento() {
    }

    public TempAlimento(Long id) {
        this.id = id;
    }

    public TempAlimento(Long id, Long id_alimento, String nombre) {
        this.id = id;
        this.id_alimento = id_alimento;
        this.nombre = nombre;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getId_alimento() {
        return id_alimento;
    }

    public void setId_alimento(Long id_alimento) {
        this.id_alimento = id_alimento;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

}
