package com.healthLife.DAO.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table TEMP_ENFERMEDAD.
 */
public class TempEnfermedad {

    private Long id;
    private Long id_enfermedad;
    private String nombre;

    public TempEnfermedad() {
    }

    public TempEnfermedad(Long id) {
        this.id = id;
    }

    public TempEnfermedad(Long id, Long id_enfermedad, String nombre) {
        this.id = id;
        this.id_enfermedad = id_enfermedad;
        this.nombre = nombre;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getId_enfermedad() {
        return id_enfermedad;
    }

    public void setId_enfermedad(Long id_enfermedad) {
        this.id_enfermedad = id_enfermedad;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

}
