package com.healthLife.DAO.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table TEMP_DIARIO.
 */
public class TempDiario {

    private Long id;
    private Long id_diario;
    private Long id_lista;
    private Long id_alimento;
    private String nombre;
    private Double calorias;
    private Double carbohidratos;
    private Double grasas;
    private Double proteinas;
    private Double total;
    private Double porcion;

    public TempDiario() {
    }

    public TempDiario(Long id) {
        this.id = id;
    }

    public TempDiario(Long id, Long id_diario, Long id_lista, Long id_alimento, String nombre, Double calorias, Double carbohidratos, Double grasas, Double proteinas, Double total, Double porcion) {
        this.id = id;
        this.id_diario = id_diario;
        this.id_lista = id_lista;
        this.id_alimento = id_alimento;
        this.nombre = nombre;
        this.calorias = calorias;
        this.carbohidratos = carbohidratos;
        this.grasas = grasas;
        this.proteinas = proteinas;
        this.total = total;
        this.porcion = porcion;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getId_diario() {
        return id_diario;
    }

    public void setId_diario(Long id_diario) {
        this.id_diario = id_diario;
    }

    public Long getId_lista() {
        return id_lista;
    }

    public void setId_lista(Long id_lista) {
        this.id_lista = id_lista;
    }

    public Long getId_alimento() {
        return id_alimento;
    }

    public void setId_alimento(Long id_alimento) {
        this.id_alimento = id_alimento;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public Double getCalorias() {
        return calorias;
    }

    public void setCalorias(Double calorias) {
        this.calorias = calorias;
    }

    public Double getCarbohidratos() {
        return carbohidratos;
    }

    public void setCarbohidratos(Double carbohidratos) {
        this.carbohidratos = carbohidratos;
    }

    public Double getGrasas() {
        return grasas;
    }

    public void setGrasas(Double grasas) {
        this.grasas = grasas;
    }

    public Double getProteinas() {
        return proteinas;
    }

    public void setProteinas(Double proteinas) {
        this.proteinas = proteinas;
    }

    public Double getTotal() {
        return total;
    }

    public void setTotal(Double total) {
        this.total = total;
    }

    public Double getPorcion() {
        return porcion;
    }

    public void setPorcion(Double porcion) {
        this.porcion = porcion;
    }

}
