package com.healthLife.DAO.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table TEMP_PERSONA.
 */
public class TempPersona {

    private Long id;
    private Long id_person;
    private String nombre;

    public TempPersona() {
    }

    public TempPersona(Long id) {
        this.id = id;
    }

    public TempPersona(Long id, Long id_person, String nombre) {
        this.id = id;
        this.id_person = id_person;
        this.nombre = nombre;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getId_person() {
        return id_person;
    }

    public void setId_person(Long id_person) {
        this.id_person = id_person;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

}
